import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Education codesandbox",
    template: "%s | Education codesandbox",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            padding: "1em",
            backgroundColor: "lightblue",
            border: "1px solid",
          }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{
            padding: "1em",
            backgroundColor: "ghostwhite",
            border: "1px solid",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
